#docker:
#  - image: node:18
#    resource_class: large
#    parallelism: 10
#steps:
#  - checkout
#  - restore_cache:
#      name: Restore pnpm Package Cache
#      keys:
#        - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
#  - run:
#      name: Build
#      command: |
#        pnpm run build
#        ls dist
#      environment:
#        TURBO_UI: "false"
#  - save_cache:
#      name: Save pnpm Package Cache
#      key: build-output-{{ .Environment.CIRCLE_SHA1 }}
#      paths:
#        - dist
#  - store_artifacts:
#      path: dist
#      destination: dist
