docker:
  - image: node:18
working_directory: ~/ci-build
steps:
  - checkout
  - restore_cache:
      name: Restore pnpm Package Cache
      keys:
        - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
  - run:
      name: Install pnpm package manager
      command: |
        corepack enable
        corepack prepare pnpm@latest-9 --activate
        pnpm config set store-dir .pnpm-store
      environment:
        TURBO_UI: "false"
  - run:
      name: Install Dependencies
      command: |
        pnpm install
      environment:
        TURBO_UI: "false"
  - save_cache:
      name: Save pnpm Package Cache
      key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
      paths:
        - .pnpm-store
  - persist_to_workspace:
      root: /home/ci
      paths:
        - ci-build
