docker:
  - image: node:18
resource_class: large
parallelism: 3
parameters:
  package:
    type: enum
    default: landing
    enum: ["app", "landing", "docs"]
steps:
  - run: echo "Running linting"
  - run: echo "Running tests"
  - run:
     name: "Set Vercel Project"
     command: |
       PROJECT_OPTION=<< pipeline.parameters.package >> | tr '[:upper:]'
       echo 'export VERCEL_PROJECT_ID="${PROJECT_OPTION}"' >> "$BASH_ENV"
  - vercel-deploy:
      vercel-project-id: $VERCEL_PROJECT_ID
      vercel-org-id: $VERCEL_ORG_ID
      vercel-token: $VERCEL_TOKEN
      requires:
        - lint
        - test
      filters:
        branches:
          ignore: /main/
      vercel-environment: preview
  - vercel-deploy:
      vercel-project-id: $VERCEL_PROJECT_ID
      vercel-org-id: $VERCEL_ORG_ID
      vercel-token: $VERCEL_TOKEN
      requires:
        - lint
        - test
      filters:
        branches:
          only: /main/
      vercel-environment: production
