version: 2.1

parameters:
  ci-shared:
    type: boolean
    default: false
  ci-app:
    type: boolean
    default: false
  ci-landing:
    type: boolean
    default: false
  ci-docs:
    type: boolean
    default: false

jobs:
  build-app:
    docker:
      - image: node:18
    working_directory: ~/ci-build
    steps:
      - run:
          name: Build app
          command: pnpm build:app
          environment:
            TURBO_UI: "false"

workflows:
  app-workflow:
    jobs:
      - setup
      - lint
      - test
      - build-app:
          requires:
            - setup

