version: 2.1

parameters:
  ci-shared:
    type: boolean
    default: false
  ci-app:
    type: boolean
    default: false
  ci-landing:
    type: boolean
    default: false
  ci-docs:
    type: boolean
    default: false

jobs:
  build-docs:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "Building app"

workflows:
  docs-workflow:
    jobs:
      - setup
      - lint # use the shared lint job.
      - test # use the shared test job.
      - build-docs
