version: 2.1

parameters:
  ci-shared:
    type: boolean
    default: false
  ci-app:
    type: boolean
    default: false
  ci-landing:
    type: boolean
    default: false
  ci-docs:
    type: boolean
    default: false

jobs:
  build-app:
    docker:
      - image: node:18
    steps:
      - checkout
      - restore_cache:
          name: Restore pnpm Package Cache
          keys:
            - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Build
          command: pnpm build:app
#          command: |
#            pnpm build:app
#            ls dist
          environment:
            TURBO_UI: "false"
#      - save_cache:
#          name: Save build output cache
#          key: build-output-{{ .Environment.CIRCLE_SHA1 }}
#          paths:
#            - dist
#      - store_artifacts:
#          path: dist
#          destination: dist

workflows:
  app-workflow:
    jobs:
      - setup
      - lint
      - test
      - build-app:
          requires:
            - setup
