version: 2.1

parameters:
  run-shared:
    type: boolean
    default: false
  run-landing:
    type: boolean
    default: false

workflows:
  app-workflow:
    jobs:
      - lint
      - test
      - build:
          package: app
