version: 2.1

parameters:
  package:
    type: enum
    enum: ["shared", "app", "landing", "docs"]

workflows:
  app-workflow:
    jobs:
      - lint
      - test
      - build:
          package: app
