version: 2.1

# use CircleCI's dynamic configuration feature
setup: true

# invoke the orbs to filter, pack and continue configs.
orbs:
  path-filtering: circleci/path-filtering@1.0.0
  circleci-cli: circleci/circleci-cli@0.1.9
  continuation: circleci/continuation@1.0.0

jobs:
  generate-config:
    executor: path-filtering/default
    steps:
      - checkout
      - circleci-cli/install
      - run:
          name: Generate shared configuration
          command: circleci config pack .circleci/shared >> .circleci/shared-config.yml
      - path-filtering/set-parameters:
          base-revision: << pipeline.git.branch >>
          mapping: |
            .* .circleci/shared-config.yml
            .* .circleci/app/config.yml
         # mapping: |
         #   .* ci-shared true .circleci/shared-config.yml
         #   apps/app/.* run-app true .circleci/app-config.yml
         #   apps/landing/.* run-landing true .circleci/landing-config.yml
         #   apps/docs/.* run-docs true .circleci/docs-config.yml
      - path-filtering/generate-config
      - run:
          name: Validate config
          command: circleci config validate /tmp/generated-config.yml
      - continuation/continue:
          configuration_path: /tmp/generated-config.yml

workflows:
  setup:
    jobs:
      - generate-config
