version: 2.1

# use CircleCI's dynamic configuration feature
setup: true

# invoke the orbs to filter, pack and continue configs.
orbs:
  path-filtering: circleci/path-filtering@1.0.0
  circleci-cli: circleci/circleci-cli@0.1.9
  continuation: circleci/continuation@1.0.0

jobs:
  generate-config:
    executor: path-filtering/default
    steps:
      - checkout
      # Install the CircleCI CLI
      - circleci-cli/install
      # Generate the shared configuration from a directory with the pack command.
      - run:
          name: Generate shared configuration
          command: circleci config pack .circleci/shared >> .circleci/shared-config.yml
      # The mapping will be used to generate the dynamic configuration for all conditions that match.
      - path-filtering/set-parameters:
          base-revision: << pipeline.git.branch >>
          config-path: .circleci/no-updates.yml
          mapping: |
            .* .circleci/shared-config.yml
            .* .circleci/landing-config.yml
         # mapping: |
         #   .* ci-shared true .circleci/shared-config.yml
         #   apps/app/.* ci-app true .circleci/app-config.yml
         #   apps/landing/.* ci-landing true .circleci/landing-config.yml
         #   apps/docs/.* ci-docs true .circleci/docs-config.yml
      # Generate the dynamic configuration based on the parameters set in the previous step.
      - path-filtering/generate-config
      # Optionally validate the generated configuration.
      - run:
          name: Validate config
          command: circleci config validate /tmp/generated-config.yml
      # Continue the pipeline with the generated configuration.
      - continuation/continue:
          configuration_path: /tmp/generated-config.yml

workflows:
  setup:
    jobs:
      - generate-config
