version: 2.1

parameters:
  run-shared:
    type: boolean
    default: false
  run-landing:
    type: boolean
    default: false
  run-app:
    type: boolean
    default: false
  run-docs:
    type: boolean
    default: false

workflows:
  docs-workflow:
    jobs:
      - lint
      - build:
          package: docs
