version: 2.1

parameters:
  package:
    type: enum
    default: landing
    enum: ["shared", "app", "landing", "docs"]

workflows:
  docs-workflow:
    jobs:
      - lint
      - build:
          package: docs
