version: 2.1

parameters:
  run-shared:
    type: boolean
    default: false
  run-landing:
    type: boolean
    default: false
  run-app:
    type: boolean
    default: false
  run-docs:
    type: boolean
    default: false

workflows:
  landing-workflow:
    jobs:
      - lint
      - test
      - deploy:
          filters:
            branches:
              ignore: /main/
          vercel-environment: preview
          &deploy-defaults
          vercel-project-id: $VERCEL_PROJECT_ID_LANDING
          vercel-org-id: $VERCEL_ORG_ID
          vercel-token: $VERCEL_TOKEN
          requires:
            - lint
            - test
      - deploy:
          filters:
            branches:
              only: /main/
          vercel-environment: production
          <<: *deploy-defaults
