version: 2.1

parameters:
  package:
    type: enum
    default: landing
    enum: ["shared", "app", "landing", "docs"]

workflows:
  landing-workflow:
    jobs:
      - lint
      - test
      - build:
          package: docs
