version: 2.1

references:
  deploy-defaults: &deploy-defaults
    vercel-project-id: $VERCEL_PROJECT_ID_LANDING
    vercel-org-id: $VERCEL_ORG_ID
    vercel-token: $VERCEL_TOKEN
    requires:
      - lint
      - test

parameters:
  package:
    type: enum
    enum: ["shared", "app", "landing", "docs"]

workflows:
  landing-workflow:
    jobs:
      - lint
      - test
      - deploy:
          <<: *deploy-defaults
          filters:
            branches:
              ignore: /main/
          vercel-environment: preview
      - deploy:
          <<: *deploy-defaults
          filters:
            branches:
              only: /main/
          vercel-environment: production
