version: 2.1

parameters:
  package:
    type: enum
    default: landing
    enum: ["app", "landing", "docs"]

jobs:
  no-updates:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "No code changes detected"

workflows:
  no-update-workflow:
    jobs:
      - no-updates
