version: 2.1

parameters:
  run-landing:
    type: boolean
    default: false

jobs:
  no-updates:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "No code changes detected"

workflows:
  no-update-workflow:
    jobs:
      - no-updates
