version: 2.1

# define the parameters from the setup config.
parameters:
  ci-shared:
    type: boolean
    default: false
  ci-app:
    type: boolean
    default: false
  ci-landing:
    type: boolean
    default: false
  ci-docs:
    type: boolean
    default: false

jobs:
  no-updates:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "No code changes detected"

workflows:
  no-update-workflow:
    jobs:
      - no-updates
