version: 2.1

parameters:
  run-shared:
    type: boolean
    default: false
  run-landing:
    type: boolean
    default: false
  run-app:
    type: boolean
    default: false
  run-docs:
    type: boolean
    default: false

workflows:
  test-and-deploy:
    jobs:
      - lint
      - test
      - set-vercel-project:
          run-shared: <<parameters.run-shared>>
          run-app: <<parameters.run-app>>
          run-landing: <<parameters.run-landing>>
          run-docs: <<parameters.run-docs>>
      - deploy:
          vercel-project-id: $VERCEL_PROJECT_ID
          vercel-org-id: $VERCEL_ORG_ID
          vercel-token: $VERCEL_TOKEN
          requires:
            - lint
            - test
          filters:
            branches:
              ignore: /main/
          vercel-environment: preview
      - deploy:
          vercel-project-id: $VERCEL_PROJECT_ID
          vercel-org-id: $VERCEL_ORG_ID
          vercel-token: $VERCEL_TOKEN
          requires:
            - lint
            - test
          filters:
            branches:
              only: /main/
          vercel-environment: production
