version: 2.1

parameters:
  run-shared:
    type: boolean
    default: false
  run-landing:
    type: boolean
    default: false
  run-app:
    type: boolean
    default: false
  run-docs:
    type: boolean
    default: false

references:
  deploy-defaults: &deploy-defaults
    vercel-project-id: $VERCEL_PROJECT_ID
    vercel-org-id: $VERCEL_ORG_ID
    vercel-token: $VERCEL_TOKEN
    requires:
      - lint
      - test

workflows:
  test-and-deploy:
    jobs:
      - lint
      - test
      - set-vercel-project
      - deploy:
          <<: *deploy-defaults
          filters:
            branches:
              ignore: /main/
          vercel-environment: preview
      - deploy:
          <<: *deploy-defaults
          filters:
            branches:
              only: /main/
          vercel-environment: production
