version: 2.1

parameters:
  run-shared:
    type: boolean
    default: false
  run-landing:
    type: boolean
    default: false
  run-app:
    type: boolean
    default: false
  run-docs:
    type: boolean
    default: false
  run-contracts:
    type: boolean
    default: false
workflows:
  run-app:
    jobs:
      - lint
      - test
      - deploy_preview_app: &base
          vercel-project-id: $VERCEL_PROJECT_ID_APP
          vercel-org-id: $VERCEL_ORG_ID
          vercel-token: $VERCEL_TOKEN
          requires:
            - lint
            - test
          vercel-environment: preview
          filters:
            branches:
              ignore: /main/
      - deploy_production_app:
          <<: *base
          vercel-environment: production
          filters:
            branches:
              only: /main/
